- name: Update homebrew.
  homebrew:
    state: latest
    update_homebrew: true

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'

- name: Install homebrew cask packages
  command: brew install --cask {{ item }}
  loop: '{{ homebrew_cask_packages }}'

- name: homebrew cleanup
  command: brew cleanup

- name: Dock left.
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left
    state: present

- name: Dock autohide.
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

- name: Kill dock for settings to take place.
  ansible.builtin.shell: |
    killall Dock
